### ISSUE TITLE
removable=0 になるとWindowsでNAFUDAドライブとして認識されなくなる

### ISSUE THREAD

**Issue by makamaka** [builderscon/electronic_badge_2018#8]
90343408debc92fb34152af0ebfbd2af36b13b3d の変更で Windows からドライブとして認識されなくなる現象が発生しました。 
1に戻すと認識されます。

**Comment by uzulla** [comment]
おおう…これは致命的ですね、ちょっとテストした上で対応を検討します。

最後に「なんかディスクドライブだとかっこ悪いな」っておもってやったことが裏目に出ました。

**Comment by uzulla** [comment]
修正を手動revertしました！ありがとうございました！

イメージリリースは手が空いたら行います。
